services:
  - type: web
    name: directus-docker
    env: docker
    region: singapore
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: postgresql://directus_db_zpxt_user:8KlFz0QYSjxaQcVexJcyPNTs2Zs1wInT@dpg-d40re17gi27c73cujtgg-a/directus_db_zpx
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        value: 123456
      - key: PORT
        value: 8080
