services:
  - type: web
    name: directus-docker
    env: docker
    region: singapore
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: postgres://USER:PASSWORD@HOST/neondb
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        value: 123456
      - key: PORT
        value: 8080
